### ISSUE TITLE
消融实验ProtoAU-w/o-AU性能问题

### ISSUE THREAD

**Issue by spnooyseed** [oceanlvr/ProtoAU#1]
你好，我对这篇论文比较感兴趣，然后拉取代码跑了一下，因为代码有问题，只跑了一个yelp2018数据集上的w/o-AU消融实验。
但是发现ProtoAU-w/o-AU recall@20（自己跑出来的）甚至不到LightGCN recall@20（论文中提供的数据）的一半，ProtoAU-w/o-AU recall@20仅有0.06
![image](https://github.com/oceanlvr/ProtoAU/assets/55803010/a9c8aae4-e81c-4836-b6d8-0efb251d87f8)
，这是我复现的场景：https://github.com/spnooyseed/ProtoAU/pull/1
运行命令为：`python index.py --gpu_id=0 --model=ProtoAU --run_name=ProtoAU --dataset=yelp2018`

运行结果为：
> wandb: Run summary:
wandb:      Hit Ratio@10 0.03072
wandb:      Hit Ratio@20 0.05356
wandb:           NDCG@10 0.04071
wandb:           NDCG@20 0.05015
wandb:      Precision@10 0.03144
wandb:      Precision@20 0.02741
wandb:         Recall@10 0.0349
wandb:         Recall@20 0.06008
wandb:        batch_loss 0.09954
wandb: best.Hit Ratio@10 0.03072
wandb: best.Hit Ratio@20 0.05356
wandb:      best.NDCG@10 0.04071
wandb:      best.NDCG@20 0.05015
wandb: best.Precision@10 0.03144
wandb: best.Precision@20 0.02741
wandb:    best.Recall@10 0.0349
wandb:    best.Recall@20 0.06008
wandb:           cl_loss 0.00187
wandb:             epoch 120
wandb:          rec_loss 0.09767

这边您是否能解答一下这个现象呢

**Comment by oceanlvr** [comment]
Hello 感谢你对我的工作的关注。
这个是论文和仓库的数据集处理方式不一致。论文中的数据处理方式是按照 NCL 原文的方式（来自 [NCL](https://github.com/RUCAIBox/NCL) ），而本仓库使用的是 SELFRec 的数据集处理方式。（在这个仓库中是更加标准的做法，来自 [SELFRec](https://github.com/Coder-Yu/SELFRec)）。

具体你可以看这个 issue https://github.com/RUCAIBox/NCL/issues/4%E3%80%82
对于 NCL 中的划分是按照 user 划分、交互数据重复不去重。导致监督信号偏高很多。我也不太认同这种处理方式，仓库上直接复用了SELFREC更有公信力。但是论文中我的主要比较对象是 NCL，所以还是沿用了他的数据处理方式。

其他还有一些细小的区别，都是主要是NCL和SelfREC处理数据集的差异，例如负采样的方式不一样 ，NCL仓库在测试阶段采用固定的负采样。（这会影响监督任务的表现） https://github.com/RUCAIBox/NCL/issues/51 

具体的你可以看下在NCL数据集处理方式和SELFREC处理方式下 数据密度的区别https://github.com/oceanlvr/ProtoAU/blob/master/dataset/helper.py

--------

其次对于 ProtoAU-w/o-au 性能小于LightGCN 问题，可能需要您调整下参数。我代码给出的不是最佳的参数，是对标 NCL 默认参数。以下是我在 yelp2018 (SELFREC版本处理处理方式，也就是本仓库代码中的 datasets/ 文件夹下处理后的数据集) 用网格搜索随机搜索10轮得到的 protoau-w/o-au 对比 LightGCN 的性能。

<img width="600" alt="image" src="https://github.com/oceanlvr/ProtoAU/assets/36698124/89b29928-75f7-42db-a9b5-baa2202eb405">


截图中的 protoau-w/o-au 的超参数：
```
model_config.proto_reg:0.000044 
model_config.temperature:0.042
model_config.num_clusters:1,500
```

**Comment by oceanlvr** [comment]
关闭issue
